build:
	javac -cp . cscie97/asn2/housemate/model/*.java cscie97/asn2/test/*.java

run:
	java -cp . cscie97.asn2.test.TestDriver ./cscie97/asn2/test/test-commands.txt

clean:
	find . -type f -name "*.class" -delete

